In [1]:
import pandas as pd
import json
from datetime import datetime

In [19]:
#path = 'export_interseguro_data.json'
path = 'export (4).json'

In [74]:
with open(path, 'r', encoding='utf-8') as archivo:
    datos_json = json.load(archivo)

In [21]:
metadada_jobs_created = datos_json['orchestrationJobs']
jobs_data = [(job['id'], datetime.utcfromtimestamp(job['created'] / 1000)) for job in metadada_jobs_created]
df = pd.DataFrame(jobs_data, columns=['ID', 'FECHA_CREACION'])

In [41]:
with open('archivo.json', 'w') as file:
    json.dump(datos_json['orchestrationJobs'][0]['components'], file)

In [67]:
datos_json['orchestrationJobs'][0]['components']

{'413392': {'id': 413392,
  'inputCardinality': 'ZERO',
  'outputCardinality': 'MANY',
  'connectorHint': 'UNCONDITIONAL',
  'executionHint': 'FLOW',
  'implementationID': 444132438,
  'x': -208,
  'y': -32,
  'width': 32,
  'height': 32,
  'inputConnectorIDs': [],
  'outputSuccessConnectorIDs': [],
  'outputFailureConnectorIDs': [],
  'outputUnconditionalConnectorIDs': [413445],
  'outputTrueConnectorIDs': [],
  'outputFalseConnectorIDs': [],
  'exportMappings': {},
  'parameters': {'1': {'slot': 1,
    'name': 'Name',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': 'Start 0'}}}},
    'visible': True}},
  'expectedFailure': None,
  'activationStatus': 'ENABLED',
  'outputIterationConnectorIDs': [],
  'inputIterationConnectorIDs': []},
 '413393': {'id': 413393,
  'inputCardinality': 'ONE',
  'outputCardinality': 'MANY',
  'connectorHint': 'SUCCESS_FAIL',
  'executionHint': 'EXECUTE',
  'implementationID': -798585337,
  'x': 192,
  'y': -32,
  'width': 32,
  'height': 32,
  'inputConnectorIDs': [413444],
  'outputSuccessConnectorIDs': [413446],
  'outputFailureConnectorIDs': [],
  'outputUnconditionalConnectorIDs': [],
  'outputTrueConnectorIDs': [],
  'outputFalseConnectorIDs': [],
  'exportMappings': {},
  'parameters': {'1': {'slot': 1,
    'name': 'Name',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': 'TRUNCATE_TD_POLIZA_SINIESTRO_PAGO_raw'}}}},
    'visible': True},
   '2': {'slot': 2,
    'name': 'SQL Script',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': 'TRUNCATE TABLE acsele_data.TD_POLIZA_SINIESTRO_PAGO_raw'}}}},
    'visible': True}},
  'expectedFailure': None,
  'activationStatus': 'ENABLED',
  'outputIterationConnectorIDs': [],
  'inputIterationConnectorIDs': []},
 '413394': {'id': 413394,
  'inputCardinality': 'ONE',
  'outputCardinality': 'MANY',
  'connectorHint': 'SUCCESS_FAIL',
  'executionHint': 'EXECUTE',
  'implementationID': -741198691,
  'x': -32,
  'y': -32,
  'width': 32,
  'height': 32,
  'inputConnectorIDs': [413445],
  'outputSuccessConnectorIDs': [413444],
  'outputFailureConnectorIDs': [],
  'outputUnconditionalConnectorIDs': [],
  'outputTrueConnectorIDs': [],
  'outputFalseConnectorIDs': [],
  'exportMappings': {},
  'parameters': {'1': {'slot': 1,
    'name': 'Name',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': 'TD_POLIZA_SINIESTRO_PAGO_landing'}}}},
    'visible': True},
   '2': {'slot': 2,
    'name': 'Database Type',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': 'PostgreSQL'}}}},
    'visible': True},
   '3': {'slot': 3,
    'name': 'Connection URL',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': '${v_CadenaConexionAcselE}'}}}},
    'visible': True},
   '6': {'slot': 6,
    'name': 'Username',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': '${v_UsuarioAcselE}'}}}},
    'visible': True},
   '7': {'slot': 7,
    'name': 'Password',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'PASSWORD', 'value': 'AcselE'}}}},
    'visible': True},
   '8': {'slot': 8,
    'name': 'SQL Query',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': "SELECT   /*+ PARALLEL(2) */\n       PRE.NUMEROPOLIZAINPUT            AS NUMERO_POLIZA\n      ,PLO.OPERATIONPK                  AS NUMERO_OPERACION\n      ,TO_CHAR(COT.AUDITDATE,'YYYY-MM-DD HH24:MI:SS') AS AUDITDATE_SYSTEM_DATE\n      ,AGR.PRODUCTID                    AS ID_PRODUCTO\n      ,TRIM(UPPER(PRO.DESCRIPTION))     AS NOMBRE_PRODUCTO\n,CLA.CLAIMNUMBER AS NUMERO_SINIESTRO\n,TRIM(UPPER(EC.DESCRIPTION))  AS CAUSA_SINIESTRO\n,TO_CHAR(CLA.POLICYDATE,'YYYY-MM-DD HH24:MI:SS') AS FECHA_SINIESTRO\n,TO_CHAR(CLA.CLAIMDATE,'YYYY-MM-DD HH24:MI:SS')  AS FECHA_CREACION_SINIESTRO\n,CLA.CLAIMID\n--,COJ.DAMAGEDCOID\n--,UPPER(TYP.DESCRIPTION) AS DESCRIPCION_ADICIONAL_SINIESTRO\n--,PAY.BENEFICIARY AS NOMBRE_BENEFICIARIO_SINIESTRADO\n,CLA.STATE  AS ESTADO_SINIESTRO\n,(CASE CLA.STATE WHEN 0 THEN 'ABIERTO'\n                 WHEN 1 THEN 'CERRADO' \n                 WHEN 2 THEN 'RECHAZADO' \n                 WHEN 3 THEN 'CANCELADO'\n                 WHEN 4 THEN 'REABIERTO' \n                 WHEN 5 THEN 'PENDIENTE' \n                 WHEN 6 THEN 'PAGADO'\n                 WHEN 7 THEN 'APROBACIONPENDIENTE'\n                 ELSE 'NO DEFINIDO' END) AS ESTADO_SINIESTRO_GLOSA\n,POR.PAYMENTORDERID\n,POR.BENEFICIARY AS NOMBRE_BENEFICIARIO\n,OI.OPENITEMID \n,LIQ.POR_ID\n,TO_CHAR(OI.OPENITEMDATE ,'YYYY-MM-DD HH24:MI:SS') AS OPENITEMDATE\n,POR.DATEPAYMENTORDER\n,POR.AMOUNT AS MONTO_PAGO\n,POR.COVERAGEDESC AS COBERTURA\n,POR.THIRDPARTYID \n,TO_CHAR(OI.DUEDATE,'YYYY-MM-DD HH24:MI:SS')  AS FECHA_PAGO\n,OI.STATUS\n,POR.FKRESERVE AS ID_RESERVA\n--,TMP.*\n       FROM INTERSEGURO.PREPOLICY PRE\n INNER JOIN INTERSEGURO.POLICYDCO PLO\n         ON PLO.DCOID = PRE.PK\n INNER JOIN INTERSEGURO.CONTEXTOPERATION COT\n         ON COT.ID =PLO.OPERATIONPK\n        AND COT.STATUS=2\n INNER JOIN INTERSEGURO.AGREGATEDPOLICY AGR\n         ON AGR.OPERATIONPK = PLO.OPERATIONPK\n INNER JOIN INTERSEGURO.PRODUCT PRO\n         ON PRO.PRODUCTID = AGR.PRODUCTID\n INNER JOIN INTERSEGURO.CLAIM CLA\n         ON CLA.POLICYID = AGR.AGREGATEDPOLICYID \n INNER JOIN INTERSEGURO.CLAIMPAYMENT CP \n         ON CP.CLAIMID = CLA.CLAIMID\n INNER JOIN INTERSEGURO.PAYMENTORDER POR\n         ON CP.CLAIMPAYMENTID = POR.CPY_ID\n LEFT JOIN INTERSEGURO.STCL_PAYMENTLIQUIDATION LIQ \n         ON POR.PAYMENTORDERID = LIQ.POR_ID\n LEFT JOIN INTERSEGURO.OPENITEM OI \n         ON LIQ.OPM_ID = OI.OPENITEMID        \n LEFT JOIN INTERSEGURO.EVENTCLAIM EC\n         ON EC.PK = CLA.EVENTCLAIMID\nWHERE PRE.NUMEROPOLIZAINPUT  IS NOT NULL"}}}},
    'visible': True},
   '9': {'slot': 9,
    'name': 'Dataset',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': '${v_DatasetAcselE}'}}}},
    'visible': True},
   '11': {'slot': 11,
    'name': 'Connection Options',
    'elements': {},
    'visible': True},
   '13': {'slot': 13,
    'name': 'Target Table',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': 'TD_POLIZA_SINIESTRO_PAGO_landing'}}}},
    'visible': True},
   '14': {'slot': 14,
    'name': 'Cloud Storage Staging Area',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': 'gs://interseguro-datalake-uat-landing/raw/ACSELE/TDTASACAMBSBS/'}}}},
    'visible': True},
   '15': {'slot': 15,
    'name': 'Load Options',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': 'On'}}},
     '2': {'slot': 2,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': ''}}},
     '3': {'slot': 3,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': 'On'}}}},
    'visible': True},
   '16': {'slot': 16,
    'name': 'Project',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': '[Environment Default]'}}}},
    'visible': True},
   '20': {'slot': 20,
    'name': 'Data Schema',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': ''}}}},
    'visible': False},
   '101': {'slot': 101,
    'name': 'Basic/Advanced Mode',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': 'Advanced'}}}},
    'visible': True},
   '102': {'slot': 102,
    'name': 'Data Source',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': ''}}}},
    'visible': False},
   '103': {'slot': 103,
    'name': 'Data Selection',
    'elements': {},
    'visible': False},
   '104': {'slot': 104,
    'name': 'Data Source Filter',
    'elements': {},
    'visible': False},
   '105': {'slot': 105,
    'name': 'Combine Filters',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': 'And'}}}},
    'visible': False},
   '106': {'slot': 106,
    'name': 'Limit',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'INTEGER', 'value': '100'}}}},
    'visible': False},
   '1001': {'slot': 1001, 'name': '', 'elements': {}, 'visible': False},
   '1996': {'slot': 1996,
    'name': 'Location',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': 'gs://<bucket>/<path>'}}}},
    'visible': False},
   '1997': {'slot': 1997,
    'name': 'New Target Table',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': ''}}}},
    'visible': False},
   '1998': {'slot': 1998,
    'name': 'Dataset',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': '[Environment Default]'}}}},
    'visible': False},
   '1999': {'slot': 1999,
    'name': 'Project',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': '[Environment Default]'}}}},
    'visible': False},
   '2000': {'slot': 2000,
    'name': 'Table Type',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1, 'type': 'STRING', 'value': 'Native'}}}},
    'visible': True}},
  'expectedFailure': None,
  'activationStatus': 'ENABLED',
  'outputIterationConnectorIDs': [],
  'inputIterationConnectorIDs': []},
 '413395': {'id': 413395,
  'inputCardinality': 'ONE',
  'outputCardinality': 'MANY',
  'connectorHint': 'SUCCESS_FAIL',
  'executionHint': 'EXECUTE',
  'implementationID': -798585337,
  'x': 432,
  'y': -32,
  'width': 32,
  'height': 32,
  'inputConnectorIDs': [413446],
  'outputSuccessConnectorIDs': [413447],
  'outputFailureConnectorIDs': [],
  'outputUnconditionalConnectorIDs': [],
  'outputTrueConnectorIDs': [],
  'outputFalseConnectorIDs': [],
  'exportMappings': {},
  'parameters': {'1': {'slot': 1,
    'name': 'Name',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': 'INSERT_TD_POLIZA_SINIESTRO_PAGO_raw'}}}},
    'visible': True},
   '2': {'slot': 2,
    'name': 'SQL Script',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': "INSERT INTO acsele_data.TD_POLIZA_SINIESTRO_PAGO_raw\n(\nNUMERO_POLIZA\n,NUMERO_OPERACION\n,AUDITDATE_SYSTEM_DATE\n,ID_PRODUCTO\n,NOMBRE_PRODUCTO\n,NUMERO_SINIESTRO\n,CAUSA_SINIESTRO\n,FECHA_SINIESTRO\n,FECHA_CREACION_SINIESTRO\n,CLAIMID\n,ESTADO_SINIESTRO\n,ESTADO_SINIESTRO_GLOSA\n,PAYMENTORDERID\n,NOMBRE_BENEFICIARIO\n,OPENITEMID\n,POR_ID\n,OPENITEMDATE\n,DATEPAYMENTORDER\n,MONTO_PAGO\n,COBERTURA\n,THIRDPARTYID\n,FECHA_PAGO\n,STATUS\n,ID_RESERVA\n)\nSELECT \nNUMERO_POLIZA\n,NUMERO_OPERACION\n,TIMESTAMP(AUDITDATE_SYSTEM_DATE,'America/Lima') as AUDITDATE_SYSTEM_DATE\n,CAST(ID_PRODUCTO AS NUMERIC) AS ID_PRODUCTO\n,NOMBRE_PRODUCTO\n,NUMERO_SINIESTRO\n,CAUSA_SINIESTRO\n,TIMESTAMP(FECHA_SINIESTRO,'America/Lima') AS FECHA_SINIESTRO\n,TIMESTAMP(FECHA_CREACION_SINIESTRO,'America/Lima') AS FECHA_CREACION_SINIESTRO\n,CLAIMID\n,ESTADO_SINIESTRO\n,ESTADO_SINIESTRO_GLOSA\n,PAYMENTORDERID\n,NOMBRE_BENEFICIARIO\n,OPENITEMID\n,POR_ID\n,TIMESTAMP(OPENITEMDATE,'America/Lima') AS OPENITEMDATE\n,DATEPAYMENTORDER\n,CAST(MONTO_PAGO AS STRING) AS MONTO_PAGO\n,COBERTURA\n,THIRDPARTYID\n,TIMESTAMP(FECHA_PAGO,'America/Lima') AS FECHA_PAGO\n,STATUS\n,ID_RESERVA\nFROM acsele_data.TD_POLIZA_SINIESTRO_PAGO_landing \n"}}}},
    'visible': True}},
  'expectedFailure': None,
  'activationStatus': 'ENABLED',
  'outputIterationConnectorIDs': [],
  'inputIterationConnectorIDs': []},
 '413400': {'id': 413400,
  'inputCardinality': 'ONE',
  'outputCardinality': 'MANY',
  'connectorHint': 'SUCCESS_FAIL',
  'executionHint': 'EXECUTE',
  'implementationID': -798585337,
  'x': 688,
  'y': -32,
  'width': 32,
  'height': 32,
  'inputConnectorIDs': [413447],
  'outputSuccessConnectorIDs': [],
  'outputFailureConnectorIDs': [],
  'outputUnconditionalConnectorIDs': [],
  'outputTrueConnectorIDs': [],
  'outputFalseConnectorIDs': [],
  'exportMappings': {},
  'parameters': {'1': {'slot': 1,
    'name': 'Name',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': 'DROP_TD_POLIZA_SINIESTRO_PAGO_landing'}}}},
    'visible': True},
   '2': {'slot': 2,
    'name': 'SQL Script',
    'elements': {'1': {'slot': 1,
      'values': {'1': {'slot': 1,
        'type': 'STRING',
        'value': 'DROP TABLE IF EXISTS acsele_data.TD_POLIZA_SINIESTRO_PAGO_landing'}}}},
    'visible': True}},
  'expectedFailure': None,
  'activationStatus': 'ENABLED',
  'outputIterationConnectorIDs': [],
  'inputIterationConnectorIDs': []}}

In [86]:
# Listas para almacenar los datos
job_names = []
job_ids = []
job_files = []

data = datos_json['jobsTree']['children'][1]['children']

for i, job in enumerate(data):
    #print(f"Nombre Carpeta: {job['name']}")
    job_file = job['name']
    #print(job_file)
    temp = datos_json['jobsTree']['children'][1]['children'][i]['jobs']
    for j, jobs_info in enumerate(temp):
        job_id = jobs_info['id']
        job_name = jobs_info['name']
        
        #print(f"Nombre Job: {jobs_info['id']},{jobs_info['name']}")
        
        job_names.append(job_name)
        job_ids.append(job_id)
        job_files.append(job_file)

IndexError: list index out of range

In [6]:
df_data = pd.DataFrame({
    'ID': job_ids,
    'NOMBRE_FILE': job_files,
    'NOMBRE_JOB': job_names
})

In [7]:
merged_df = pd.merge(df_data, df, on='ID', suffixes=('_left', '_right'), how='inner')

In [8]:
merged_df

,ID,NOMBRE_FILE,NOMBRE_JOB,FECHA_CREACION
0,1124,ingesta_salvadb_data,delta_salvadb_data,2024-04-01 20:54:13.259
1,1137,ingesta_salvadb_data,job_salvadb,2024-04-01 20:54:13.272
2,1161,ingesta_salvadb_data,migracion_salvadb_data,2024-04-01 20:54:13.283
3,1171,ingesta_salvadb_data,Job_coverage,2024-04-01 20:54:13.291
4,1181,ingesta_salvadb_data,Job_coverage_plan,2024-04-01 20:54:13.296
...,...,...,...,...
623,9134,ingesta_azman_data,main_azman_maestra,2024-04-01 20:54:17.715
624,9141,ingesta_alloydb_data,test_alloydb,2024-04-01 20:54:17.717
625,9151,ingesta_alloydb_data,pagado_hasta,2024-04-01 20:54:17.721
626,9162,logs_matillion,Logs_matillion,2024-04-01 20:54:17.724
627,9168,logs_matillion,transformacion_logs,2024-04-01 20:54:17.728